baseURL: "https://paulabings.org" 
title: Paula Bings
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

# menu:
#     main:
        # - name: Books
        #   url: books/
        #   weight: 5 
        # - name: Papers
        #   url: papers/
        #   weight: 2
        # - name: Courses
        #   url: courses/
        #   weight: 3
        # - name: Data
        #   url: data/
        #   weight: 4 
        # - name: Blog
        #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
        #   weight: 6

params:
    description: "Personal website"
    author: Paula Bings
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    # MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Paula Bings
          subtitle: "Hi, my name is Paula! I am a PhD fellow in Political Science at Aarhus University. I study local public service provision and political behavior. 
          Please feel free to get in touch: pnb[at]ps.au.dk!"
          imageUrl: "me.jpeg"
          imageWidth: 160
          imageHeight: 160
          # buttons:
            # - name: Papers
            #   url: papers/
            # - name: Data
            #   url: data/
            # - name: Books
            #   url: books/
            # - name: Courses
            #   url: courses/
            # - name: Tags
            #   url: tags/
            # - name: Archive
            #   url: archive/
            # - name: Blog
            #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: Location
          url: https://www.au.dk/en/pnb@ps.au.dk/
        # - name: CV
        #   url: cv.pdf
        - name: Twitter
          url: https://x.com/paulabings
        - name: Bluesky
          url: https://bsky.app/profile/paulabings.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Paula Bings"
      # icon: favicon.ico
      # iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2